go test -v github.com/ilius/qt
go test -v github.com/ilius/qt/androidextras
go test -v github.com/ilius/qt/bluetooth
go test -v github.com/ilius/qt/charts
go test -v github.com/ilius/qt/cmd/env
go test -v github.com/ilius/qt/cmd/qtdeploy
go test -v github.com/ilius/qt/cmd/qtminimal
go test -v github.com/ilius/qt/cmd/qtmoc
go test -v github.com/ilius/qt/cmd/qtrcc
go test -v github.com/ilius/qt/cmd/qtsetup
go test -v github.com/ilius/qt/core
go test -v github.com/ilius/qt/datavisualization
go test -v github.com/ilius/qt/dbus
go test -v github.com/ilius/qt/designer
go test -v github.com/ilius/qt/felgo
go test -v github.com/ilius/qt/flutter
go test -v github.com/ilius/qt/gamepad
go test -v github.com/ilius/qt/gui
go test -v github.com/ilius/qt/help
go test -v github.com/ilius/qt/internal
go test -v github.com/ilius/qt/internal/binding/converter
go test -v github.com/ilius/qt/internal/binding/files/docs
go test -v github.com/ilius/qt/internal/binding/parser
go test -v github.com/ilius/qt/internal/binding/runtime
go test -v github.com/ilius/qt/internal/binding/templater
go test -v github.com/ilius/qt/internal/cmd
go test -v github.com/ilius/qt/internal/cmd/deploy
go test -v github.com/ilius/qt/internal/cmd/minimal
go test -v github.com/ilius/qt/internal/cmd/moc
go test -v github.com/ilius/qt/internal/cmd/moc/test
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/b
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/bgo
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/c
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/cgo
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/conf
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/d
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/dgo
go test -v github.com/ilius/qt/internal/cmd/moc/test/sub/subsub
go test -v github.com/ilius/qt/internal/cmd/rcc
go test -v github.com/ilius/qt/internal/cmd/setup
go test -v github.com/ilius/qt/internal/utils
go test -v github.com/ilius/qt/interop
go test -v github.com/ilius/qt/interop/dart
go test -v github.com/ilius/qt/interop/gow
go test -v github.com/ilius/qt/interop/haxe
go test -v github.com/ilius/qt/interop/swift
go test -v github.com/ilius/qt/location
go test -v github.com/ilius/qt/macextras
go test -v github.com/ilius/qt/multimedia
go test -v github.com/ilius/qt/network
go test -v github.com/ilius/qt/nfc
go test -v github.com/ilius/qt/positioning
go test -v github.com/ilius/qt/printsupport
go test -v github.com/ilius/qt/purchasing
go test -v github.com/ilius/qt/qml
go test -v github.com/ilius/qt/quick
go test -v github.com/ilius/qt/quickcontrols2
go test -v github.com/ilius/qt/remoteobjects
go test -v github.com/ilius/qt/sailfish
go test -v github.com/ilius/qt/script
go test -v github.com/ilius/qt/scripttools
go test -v github.com/ilius/qt/scxml
go test -v github.com/ilius/qt/sensors
go test -v github.com/ilius/qt/serialbus
go test -v github.com/ilius/qt/serialport
go test -v github.com/ilius/qt/speech
go test -v github.com/ilius/qt/sql
go test -v github.com/ilius/qt/svg
go test -v github.com/ilius/qt/testlib
go test -v github.com/ilius/qt/uitools
go test -v github.com/ilius/qt/virtualkeyboard
go test -v github.com/ilius/qt/webchannel
go test -v github.com/ilius/qt/webengine
go test -v github.com/ilius/qt/webkit
go test -v github.com/ilius/qt/websockets
go test -v github.com/ilius/qt/webview
go test -v github.com/ilius/qt/widgets
go test -v github.com/ilius/qt/xml